- name: "Install MySQL CLI client (debian based systems)"
  package: 
    name: "{{ proxysql_debian_cli_client_package }}"
  when: proxysql_cli_install_client and ansible_os_family == 'Debian'

- name: "Install MySQL CLI client (red hat based systems)"
  package: 
    name: "{{ proxysql_redhat_cli_client_package }}"
  when: proxysql_cli_install_client and ansible_os_family == 'RedHat'

- name: "Write configuration file"
  template:
    src: "root_my.cnf.j2"
    dest: "{{ proxysql_cli_config_path }}"
  when: proxysql_cli_install_config
