- name: "Check parameters upgraded"
  assert:
    that: 
     - "proxysql_admin_credentials is not defined"
     - "proxysql_admin_ifaces is not defined"
    fail_msg: "Please upgrade your group vars to the new style configuration"


- name: Ensure lsb-release is installed.
  apt: name=lsb-release state=present


- name: Ensure group "proxysql" exists
  group:
    name: proxysql
    state: present


- name: Ensure the user "proxysql" exists
  user:
    name: proxysql
    group: proxysql


- name: Create a directory for the pid file
  file:
    path: /var/run/proxysql
    state: directory
    owner: proxysql
    group: proxysql


- name: APT | Install ProxySQL key
  apt_key:
    url: https://repo.proxysql.com/ProxySQL/repo_pub_key
    state: present


- name: APT | Add ProxySQL repository
  apt_repository: repo='deb https://repo.proxysql.com/ProxySQL/proxysql-2.0.x/{{ ansible_distribution_release }}/ ./' state=present


- name: Install, upgrade or downgrade ProxySQL
  apt: 
    name: "proxysql{{ ('=' + proxysql_apt_version) if proxysql_apt_version|length > 0 }}"
    state: "{{ 'latest' if proxysql_apt_version|length == 0 else 'present' }}"
    force: yes # Allow downgrades


- name: Recursively change ownership of /var/lib/proxysql folder
  file:
    path: /var/lib/proxysql
    state: directory
    recurse: yes
    owner: proxysql
    group: proxysql



### Configuration


- name: Copy ProxySQL config file
  template:
    src: "{{ proxysql_template }}"
    dest: "{{ proxysql_cnf_path }}/proxysql.cnf"
    owner: proxysql
    group: proxysql
    mode: 0644
  notify: Restart ProxySQL
  register: config


- name: Remove current configuration
  file:
    path: /var/lib/proxysql/proxysql.db
    state: absent
  when: config.changed

- name: "Installing CLI client and/or admin interface configuration"
  import_tasks: admin-client.yml
  when: proxysql_cli_install_client or proxysql_cli_install_config

- name: "Installing health check on Galera Cluster nodes"
  include_tasks: install-health-check.yml
  when: proxysql_cli_install_client and proxysql_cli_install_config and proxysql_install_health_check
  loop: "{{ proxysql_mysql_galera_hostgroups }}"

- name: "Install work-around for issue 1254"
  template:
    src: template/cron_ansible_1254_workaround.j2
    dest: /etc/cron.d/ansible_1254_workaround
  when: proxysql_cli_install_config and proxysql_install_1254_workaround
