- name: "Check parameters upgraded"
  assert:
    that: 
     - "proxysql_admin_credentials is not defined"
     - "proxysql_admin_ifaces is not defined"
    fail_msg: "Please upgrade your group vars to the new style configuration"


- name: Ensure group "proxysql" exists
  group:
    name: proxysql
    state: present


- name: Ensure the user "proxysql" exists
  user:
    name: proxysql
    group: proxysql


- name: Create a directory for the pid file
  file:
    path: /var/run/proxysql
    state: directory
    owner: proxysql
    group: proxysql


- name: Recursively change ownership of /var/lib/proxysql folder
  file:
    path: /var/lib/proxysql
    state: directory
    recurse: yes
    owner: proxysql
    group: proxysql

- name: "ProxySQL - Install on Red Hat based systems"
  import_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'
      
- name: "ProxySQL - Install on Debian based systems"
  import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'


### Configuration
- name: Copy ProxySQL config file
  template:
    src: "{{ proxysql_template }}"
    dest: "{{ proxysql_cnf_path }}/proxysql.cnf"
    owner: proxysql
    group: proxysql
    mode: 0644
  notify: Restart ProxySQL
  register: config


- name: Remove current configuration
  file:
    path: /var/lib/proxysql/proxysql.db
    state: absent
  when: config.changed

- name: "Installing CLI client and/or admin interface configuration"
  import_tasks: admin-client.yml
  when: proxysql_cli_install_client or proxysql_cli_install_config

- name: "Installing health check on Galera Cluster nodes"
  include_tasks: install-health-check.yml
  when: proxysql_cli_install_client and proxysql_cli_install_config and proxysql_install_galera_health_check and proxysql_mysql_galera_hostgroups
  loop: "{{ proxysql_mysql_galera_hostgroups }}"

- name: "Install any host online health check when not installing galera health check"
  when: "proxysql_install_any_host_online_health_check"
  include_tasks: install-health-check.yml
  vars:
    item:
      health_check_port: "{{ proxysql_any_host_online_health_check_port | default(9300) }}"
      health_check_type: "any_host_online"
      
- name: "Install work-around for issue 1254"
  template:
    src: templates/cron_ansible_1254_workaround.j2
    dest: /etc/cron.d/ansible_1254_workaround
  when: proxysql_cli_install_config and proxysql_install_1254_workaround

- name: "Remove work-around for issue 1254"
  file:
    path: /etc/cron.d/ansible_1254_workaround
    state: absent
  when: not proxysql_install_1254_workaround
