---
# handlers file for proxySQL

- name: Restart ProxySQL
  service:
    name: proxysql
    state: restarted


- name: Reload systemd
  systemd:
    daemon_reload: yes
  ignore_errors: True  # Allow to fail on systems without systemd
